(() => {
'use strict';
const $=s=>document.querySelector(s), state=()=>EP.state;
const inPages=location.pathname.includes('/pages/'), base=inPages?'../':'';
const page=location.pathname.split('/').pop().replace('.html','') || 'index';
const route=page==='index'?'attendee-session-catalog':page;
const groups={attendee:['Người tham dự',[['session-catalog','Khám phá session','▦'],['my-agenda','Lịch của tôi','◷'],['session-feedback','Phản hồi','▤']]],speaker:['Diễn giả',[['profile','Hồ sơ diễn giả','◎'],['my-session','Session của tôi','▦'],['session-materials','Tài liệu trình bày','▤'],['session-insights','Session insights','↗']]],organizer:['Ban tổ chức',[['session-management','Quản lý session','▦'],['room-management','Quản lý phòng','▣'],['event-alerts','Thông báo sự kiện','♧'],['interest-forecast','Dự báo quan tâm','↗']]],admin:['Quản trị viên',[['ticket-type-management','Loại vé','▤'],['user-management','Người dùng','◎'],['event-analytics','Phân tích sự kiện','↗'],['system-settings','Cấu hình & Audit','⚙']]]};
const role=route.split('-')[0] in groups?route.split('-')[0]:'attendee';
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url=(r,query='')=>`${base}pages/${r}.html${query}`;
const link=(r,label,cls='',query='')=>`<a class="button ${cls}" href="${url(r,query)}">${label}</a>`;
const btn=(action,label,id='',cls='')=>`<button type="button" class="${cls}" data-action="${action}" data-id="${id}" ${action==='notifications'?'aria-label="Thông báo"':action==='close'?'aria-label="Đóng hộp thoại"':''}>${label}</button>`;
const badge=(text,bad=false)=>`<span class="status ${bad?'bad':''}">${e(text)}</span>`;
const empty=text=>`<div class="empty"><strong>${text}</strong>Thử thay đổi bộ lọc hoặc thêm dữ liệu mới.</div>`;
const money=n=>Number(n).toLocaleString('vi-VN')+' ₫';
const sessions=()=>state().sessions.filter(s=>s.status!=='Đã hủy');
const agenda=()=>sessions().filter(s=>state().agenda.includes(s.id));
const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${headers.length}">${empty('Chưa có dữ liệu')}</td></tr>`}</tbody></table></div>`;
const field=(name,label,value='',type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" value="${e(value)}" ${extra}></label>`;
const select=(name,label,options,value='')=>`<label>${label}<select name="${name}">${options.map(o=>`<option value="${e(o)}" ${o===value?'selected':''}>${e(o)}</option>`).join('')}</select></label>`;
let toastTimer;function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
let storageFailed=false;window.addEventListener('storage-error',()=>{storageFailed=true;toast('Không thể lưu LocalStorage. Thay đổi chỉ giữ trong phiên hiện tại.');});
function persist(message){storageFailed=false;EP.save(message);if(!storageFailed)toast(message);}
function modal(title,html){$('#modal').innerHTML=`<div class="modal-head"><h2>${title}</h2>${btn('close','✕')}</div>${html}`;$('#modal').showModal();}
function heading(title,description,action=''){return `<div class="page-heading"><div><h1>${title}</h1><p>${description}</p></div>${action}</div>`;}
function shell(){
 const title=route==='attendee-session-detail'?'Chi tiết session':groups[role][1].find(([p])=>route===role+'-'+p)?.[1]||'Không tìm thấy';
 $('#app').innerHTML=`<aside class="sidebar" id="sidebar"><a href="${base}index.html" class="brand"><img src="${base}assets/icons/pulse.svg" alt="">EventPulse</a><div class="event-box"><span class="eyebrow">Sự kiện hiện tại</span><strong>${e(state().settings.event)}</strong><small>18–20 tháng 10 · ${e(state().settings.location)}</small></div><nav class="nav" aria-label="Điều hướng chính">${groups[role][1].map(([p,t,i])=>`<a href="${url(role+'-'+p)}" class="${route===role+'-'+p?'active':''}" ${route===role+'-'+p?'aria-current="page"':''}><span class="nav-icon" aria-hidden="true">${i}</span>${t}</a>`).join('')}${role==='attendee'?`<a href="#" data-action="notifications"><span class="nav-icon">♧</span>Thông báo</a>`:''}</nav><div class="sidebar-bottom"><div class="help"><strong>ⓘ Trợ giúp & BTL-32</strong><p>Khám phá, lên lịch và kết nối tại Vietnam Tech Summit.</p>${btn('help','Hướng dẫn demo','','link')}</div><label class="role-label" for="role">Chuyển vai trò demo</label><select id="role">${Object.entries(groups).map(([k,[t]])=>`<option value="${k}" ${role===k?'selected':''}>${t}</option>`).join('')}</select></div></aside><div class="shell"><header class="topbar"><div class="top-actions"><button class="menu-toggle" data-action="menu" aria-label="Mở điều hướng" aria-expanded="false">☰</button><div class="breadcrumb">⌂ &nbsp; ${groups[role][0]} / <strong>${title}</strong></div></div><div class="top-actions"><span class="demo-label">FRONTEND DEMO · 2026</span>${btn('notifications','♧')}<span class="avatar">${role==='attendee'?'NA':role==='speaker'?'MA':role==='organizer'?'BT':'AD'}</span></div></header><main id="content" tabindex="-1"></main></div>`;
 $('#role').addEventListener('change',ev=>location.href=url(ev.target.value+'-'+groups[ev.target.value][1][0][0]));
}
function card(s){const saved=state().agenda.includes(s.id),wait=state().waitlist.includes(s.id),full=s.booked>=s.capacity;return `<article class="session-card"><div class="cover"><img src="${base}assets/images/${s.image}-session.jpg" alt="Diễn giả và khán giả tại hội thảo" loading="lazy"><span class="tag">${e(s.topic)}</span><span class="status ${full?'bad':s.booked/s.capacity>.9?'warn':''}">${full?'Đã đầy':s.booked/s.capacity>.9?'Sắp đầy':'Còn chỗ'}</span></div><h3>${e(s.title)}</h3><div class="speaker-line"><span class="avatar">${e(s.speaker.split(' ').slice(-2).map(n=>n[0]).join(''))}</span>${e(s.speaker)}</div><div class="meta"><span>◷ ${e(s.start)}–${e(s.end)} · ${e(s.room)}</span><strong>${s.booked}/${s.capacity} chỗ</strong></div><progress value="${s.booked}" max="${s.capacity}" aria-label="Số chỗ đã đặt"></progress><div class="card-actions">${link('attendee-session-detail','Xem chi tiết','',`?id=${s.id}`)}${btn(saved?'remove-agenda':full?'waitlist':'add-agenda',saved?'✓ Đã thêm':full?(wait?'✓ Đang chờ':'+ Tham gia chờ'):'+ Thêm lịch',s.id,'primary')}</div></article>`;}
function catalog(){
 $('#content').innerHTML=heading('Khám phá session','Tìm nội dung phù hợp và giữ chỗ trước khi hết sức chứa.',link('attendee-my-agenda',`◷ Lịch của tôi · ${agenda().length}`))+`<div class="banner"><div><strong>✧ Tìm session phù hợp với bạn</strong><p>Gợi ý dựa trên chủ đề quan tâm và lịch trình cá nhân.</p></div>${btn('recommend','Xem gợi ý','','link')}</div><div class="panel toolbar"><label class="search">Tìm kiếm<input id="search" placeholder="Tìm tên session, diễn giả…" type="search"></label><label>Ngày<select id="date"><option value="">Tất cả ngày</option><option value="2026-10-19">19/10/2026</option><option value="2026-10-20">20/10/2026</option></select></label><label>Chủ đề<select id="topic"><option value="">Tất cả chủ đề</option>${[...new Set(sessions().map(s=>s.topic))].map(t=>`<option>${e(t)}</option>`).join('')}</select></label><label>Diễn giả<select id="speaker"><option value="">Tất cả diễn giả</option>${[...new Set(sessions().map(s=>s.speaker))].map(t=>`<option>${e(t)}</option>`).join('')}</select></label><label>Sức chứa<select id="availability"><option value="">Tất cả trạng thái</option><option value="available">Còn chỗ</option></select></label>${btn('reset-filters','Đặt lại')}</div><div class="section-line"><strong id="count"></strong><div>${btn('grid','▦ Lưới')}${btn('list','☷ Danh sách')}</div></div><div id="catalog" class="cards"></div>`;
 for(const id of ['search','date','topic','speaker','availability'])$('#'+id).addEventListener('input',filterCatalog);filterCatalog();
}
function filterCatalog(){const q=$('#search').value.trim().toLocaleLowerCase('vi');const rows=sessions().filter(s=>(s.title+' '+s.speaker).toLocaleLowerCase('vi').includes(q)&&(!$('#date').value||s.date===$('#date').value)&&(!$('#topic').value||s.topic===$('#topic').value)&&(!$('#speaker').value||s.speaker===$('#speaker').value)&&(!$('#availability').value||s.booked<s.capacity));$('#count').textContent=`${rows.length} session · Vietnam Tech Summit 2026`;$('#catalog').innerHTML=rows.map(card).join('')||empty('Không tìm thấy session');}
function detail(){const s=sessions().find(s=>s.id===Number(new URLSearchParams(location.search).get('id')||1));if(!s){$('#content').innerHTML=empty('Session không tồn tại hoặc đã hủy')+link('attendee-session-catalog','Về danh mục');return;}
 $('#content').innerHTML=heading('Chi tiết session','Thông tin đầy đủ trước khi thêm vào agenda cá nhân.',link('attendee-session-catalog','← Quay lại danh mục'))+`<div class="two-col"><section class="panel"><img class="detail-cover" src="${base}assets/images/${s.image}-session.jpg" alt="Hội thảo công nghệ"><p><span class="tag">${e(s.topic)}</span></p><h2 style="font-size:27px">${e(s.title)}</h2><div class="facts"><span>▦ ${e(s.date)}</span><span>◷ ${e(s.start)}–${e(s.end)}</span><span>⌖ ${e(s.room)}</span><span>${s.booked}/${s.capacity} chỗ</span></div><h2>Về session</h2><p>${e(s.description)}</p><hr><h2>Diễn giả</h2><div class="speaker-line"><span class="avatar">${e(s.speaker.split(' ').pop()[0])}</span><strong>${e(s.speaker)}</strong></div></section><aside class="stack"><section class="panel"><h2>Giữ chỗ của bạn</h2><p>${Math.max(0,s.capacity-s.booked)} chỗ còn lại · ${Math.round(s.booked/s.capacity*100)}% đã đặt</p><progress value="${s.booked}" max="${s.capacity}" aria-label="Sức chứa"></progress><hr>${state().agenda.includes(s.id)?btn('remove-agenda','Bỏ khỏi agenda',s.id):btn(s.booked>=s.capacity?'waitlist':'add-agenda',s.booked>=s.capacity?(state().waitlist.includes(s.id)?'Hủy chờ':'Tham gia chờ'):'Thêm vào agenda',s.id,'primary')}<p class="muted">${agenda().some(a=>a.id!==s.id&&EventAI.overlap(a,s))?'⚠ Trùng lịch với session trong agenda.':'✓ Không trùng với lịch hiện tại.'}</p></section><section class="panel"><h2>Thông tin phòng</h2><p>${e(s.room)} · Khu Conference</p><small>♿ Lối đi thang máy · Hỗ trợ tiếp cận</small></section></aside></div>`;
}
function myAgenda(){const items=agenda().sort((a,b)=>a.start.localeCompare(b.start));const conflicts=EventAI.conflicts(items);$('#content').innerHTML=heading('Agenda của tôi',`Lịch cá nhân · ${items.length} session · 19/10/2026`,link('attendee-session-catalog','+ Thêm session'))+(conflicts.length?`<div class="banner warning"><div><strong>⚠ Phát hiện ${conflicts.length} xung đột</strong><p>Hai session trùng thời gian. Xem đề xuất để điều chỉnh.</p></div>${btn('resolve','Giải quyết ngay','','primary')}</div>`:'')+`<div class="two-col"><section class="panel"><div class="section-line"><h2>Thứ Hai, 19 tháng 10</h2>${btn('export-agenda','Xuất CSV')}</div>${items.map(s=>`<article class="timeline-item"><time>${e(s.start)}</time><div class="body"><h3>${e(s.title)}</h3><small>${e(s.start)}–${e(s.end)} · ${e(s.room)} · ${e(s.speaker)}</small></div>${btn('remove-agenda','Bỏ lịch',s.id)}</article>`).join('')||empty('Agenda của bạn đang trống')}</section><aside class="stack"><section class="panel"><h2>✧ Conflict Resolver</h2><p>Kiểm tra thời gian và ưu tiên giữ session bắt đầu sớm hơn. Bạn xem đề xuất trước khi áp dụng.</p>${btn('resolve','Kiểm tra lịch','','primary')}<p class="ai-note">AI mô phỏng · Không kiểm tra thời gian di chuyển giữa phòng.</p></section><section class="panel"><h2>Danh sách chờ</h2>${state().waitlist.map(id=>{const s=sessions().find(s=>s.id===id);return s?`<p>${e(s.title)}</p>${btn('waitlist','Hủy chờ',id)}`:'';}).join('')||'<p class="muted">Bạn chưa tham gia danh sách chờ.</p>'}</section></aside></div>`;}
function feedback(){const draft=state().feedback.find(f=>f.id==='personal')||{};$('#content').innerHTML=heading('Phản hồi session','Phản hồi được tổng hợp ẩn danh để cải thiện trải nghiệm.')+`<div class="two-col"><section class="panel"><form id="feedback-form" class="stack">${select('sessionId','Session *',sessions().map(s=>s.id+' · '+s.title),draft.sessionId?sessions().find(s=>s.id===draft.sessionId)?.id+' · '+sessions().find(s=>s.id===draft.sessionId)?.title:'')}${select('rating','Mức độ hài lòng *',['5 · Xuất sắc','4 · Rất tốt','3 · Tốt','2 · Cần cải thiện','1 · Chưa hài lòng'],draft.rating?draft.rating+' · '+['','Chưa hài lòng','Cần cải thiện','Tốt','Rất tốt','Xuất sắc'][draft.rating]:'')}<label>Điều bạn ấn tượng / góp ý *<textarea name="comment" required minlength="20" maxlength="2000" placeholder="Chia sẻ ít nhất 20 ký tự">${e(draft.comment||'')}</textarea></label><div class="form-actions">${btn('draft-feedback','Lưu nháp')}${btn('delete-feedback','Xóa phản hồi','','danger')}<button class="primary" type="submit">Gửi phản hồi</button></div></form></section><aside class="panel"><h2>Trạng thái phản hồi</h2>${badge(draft.status||'Chưa gửi')}<p>Nhận xét cần ít nhất 20 ký tự và tối đa 2.000 ký tự.</p><p class="muted">Demo cho phép sửa hoặc xóa phản hồi đã gửi. Không gửi dữ liệu tới máy chủ.</p></aside></div>`;$('#feedback-form').addEventListener('submit',ev=>{ev.preventDefault();saveFeedback('Đã gửi');});}
function saveFeedback(status){const form=$('#feedback-form');if(status==='Đã gửi'&&(!form.reportValidity()||form.elements.comment.value.trim().length<20)){toast('Nhận xét cần ít nhất 20 ký tự có nội dung.');return;}const d=new FormData(form);const previous=state().feedback.find(f=>f.id==='personal');const sessionId=parseInt(d.get('sessionId'));if(previous?.status==='Đã gửi'){const old=state().sessions.find(s=>s.id===previous.sessionId);if(old)old.feedbackCount=Math.max(0,old.feedbackCount-1);}state().feedback=state().feedback.filter(f=>f.id!=='personal');state().feedback.push({id:'personal',sessionId,rating:parseInt(d.get('rating')),comment:d.get('comment').trim(),status});if(status==='Đã gửi')state().sessions.find(s=>s.id===sessionId).feedbackCount++;persist(status==='Đã gửi'?'Gửi phản hồi thành công · FB-2048':'Đã lưu nháp');render();}
function profile(){const p=state().profile;$('#content').innerHTML=heading('Hồ sơ diễn giả','Thông tin hiển thị cho người tham dự tại sự kiện.')+`<div class="two-col"><section class="panel"><h2>Thông tin cá nhân</h2><form id="profile-form" class="form-grid">${field('name','Họ tên *',p.name,'text','required maxlength="100"')}${field('email','Email *',p.email,'email','required')}${field('position','Chức danh *',p.position,'text','required maxlength="200"')}<label class="full">Giới thiệu *<textarea name="bio" required maxlength="2000">${e(p.bio)}</textarea></label><div class="form-actions full"><button type="submit" class="primary">Lưu hồ sơ</button></div></form></section><aside class="panel"><span class="avatar" style="width:72px;height:72px;font-size:24px">MA</span><h2 style="margin-top:16px">${e(p.name)}</h2><p>${e(p.position)}</p><p class="muted">${e(p.bio)}</p></aside></div>`;$('#profile-form').addEventListener('submit',ev=>{ev.preventDefault();const data=Object.fromEntries(new FormData(ev.target));if(!data.name.trim()||!data.position.trim()||!data.bio.trim()){toast('Vui lòng nhập đủ thông tin có nội dung.');return;}const previous=state().profile.name;state().profile=data;state().sessions.filter(s=>s.speaker===previous).forEach(s=>s.speaker=data.name);state().users.filter(u=>u.name===previous).forEach(u=>{u.name=data.name;u.email=data.email;});persist('Đã cập nhật hồ sơ');render();});}
const ownSessions=()=>sessions().filter(s=>s.speaker===state().profile.name);
function speakerSessions(){const rows=ownSessions();$('#content').innerHTML=heading('Session của tôi','Theo dõi nội dung, lịch trình và trạng thái bài trình bày.')+`<div class="panel">${table(['Session','Lịch trình','Trạng thái','Thao tác'],rows.map(s=>`<tr><td><strong>${e(s.title)}</strong><br><small>${e(s.room)}</small></td><td>${e(s.start)}–${e(s.end)}</td><td>${badge(s.status)}</td><td>${btn('speaker-edit','Chỉnh sửa',s.id)} ${link('speaker-session-materials','Tài liệu')}</td></tr>`))}</div>`;}
function materials(){$('#content').innerHTML=heading('Tài liệu trình bày','Quản lý slide và tài liệu chia sẻ cho session của bạn.')+`<div class="two-col"><section class="panel"><h2>Tải tài liệu</h2><form id="material-form" class="stack">${select('sessionId','Session *',ownSessions().map(s=>s.id+' · '+s.title))}<label>Tệp PDF / PPT / PPTX *<input type="file" name="file" accept=".pdf,.ppt,.pptx" required></label><small>Tối đa 10 MB. Demo lưu tên, dung lượng và session; không lưu nội dung tệp.</small><button type="submit" class="primary" ${ownSessions().length?'':'disabled'}>Lưu thông tin tài liệu</button></form></section><section class="panel"><h2>Tài liệu đã lưu</h2><div class="stack">${state().materials.map(m=>`<div class="file-row"><div><strong>${e(m.name)}</strong><br><small>${(m.size/1024).toFixed(0)} KB · ${e(state().sessions.find(s=>s.id===m.sessionId)?.title||'')}</small></div>${btn('delete-material','Xóa',m.id,'danger')}</div>`).join('')||empty('Chưa có tài liệu')}</div></section></div>`;$('#material-form').addEventListener('submit',ev=>{ev.preventDefault();const file=ev.target.elements.file.files[0];if(!file||! /\.(pdf|ppt|pptx)$/i.test(file.name)||file.size>10*1024*1024||file.size===0){toast('Chọn tệp PDF/PPT/PPTX có dung lượng từ 1 byte đến 10 MB.');return;}state().materials.push({id:Date.now(),name:file.name,size:file.size,sessionId:parseInt(ev.target.elements.sessionId.value)});persist('Đã lưu thông tin tài liệu');render();});}
function insights(){const own=ownSessions();const replies=state().feedback.filter(f=>f.status==='Đã gửi'&&own.some(s=>s.id===f.sessionId));$('#content').innerHTML=heading('Session insights','Theo dõi phản hồi thực tế được nhập trong demo.')+stats([['Session của bạn',own.length],['Lượt đặt',own.reduce((n,s)=>n+s.booked,0)],['Phản hồi mới',replies.length],['Điểm trung bình',replies.length?(replies.reduce((n,f)=>n+f.rating,0)/replies.length).toFixed(1):'—']])+`<div class="panel"><h2>Phản hồi ẩn danh</h2>${replies.map(f=>`<div class="alert-item"><div class="stars">${'★'.repeat(f.rating)}</div><p>${e(f.comment)}</p><small>${e(own.find(s=>s.id===f.sessionId)?.title)}</small></div>`).join('')||empty('Chưa có phản hồi mới')}</div>`;}
function stats(rows){return `<div class="stats">${rows.map(([title,value])=>`<div class="stat"><small>${title}</small><strong>${value}</strong><small>Vietnam Tech Summit 2026</small></div>`).join('')}</div>`;}
function management(kind){
 const configs={sessions:['Quản lý session','Tạo và điều phối các phiên trong sự kiện.',['Session / Diễn giả','Lịch trình / Phòng','Trạng thái','Thao tác']],rooms:['Quản lý phòng','Theo dõi sức chứa và lịch sử dụng phòng.',['Phòng','Sức chứa','Vị trí','Thao tác']],users:['Quản lý người dùng','Quản lý hồ sơ và vai trò trong bản demo.',['Người dùng','Email','Vai trò / Trạng thái','Thao tác']],tickets:['Quản lý loại vé','Thiết lập giá vé, số lượng và trạng thái bán.',['Loại vé','Giá vé','Số lượng / Trạng thái','Thao tác']]};
 const [title,desc,headers]=configs[kind];$('#content').innerHTML=heading(title,desc,btn('create-'+kind,'+ Thêm mới','','primary'))+`<div class="panel"><div class="toolbar"><label class="search">Tìm kiếm<input id="manage-search" type="search" placeholder="Tìm ${title.toLowerCase()}…"></label>${btn('export-'+kind,'Xuất CSV')}</div><hr><div id="management-table"></div></div>`;
 function update(){const q=$('#manage-search').value.toLocaleLowerCase('vi');const rows=state()[kind].filter(x=>JSON.stringify(x).toLocaleLowerCase('vi').includes(q));$('#management-table').innerHTML=table(headers,rows.map(x=>{let cells=[];if(kind==='sessions')cells=[`<strong>${e(x.title)}</strong><br><small>${e(x.speaker)}</small>`,`${e(x.date)} · ${e(x.start)}–${e(x.end)}<br>${e(x.room)}`,badge(x.status,x.status==='Đã hủy')];if(kind==='rooms')cells=[e(x.name),x.capacity+' chỗ',e(x.location)];if(kind==='users')cells=[e(x.name),e(x.email),e(x.role)+'<br>'+badge(x.status,x.status==='Tạm khóa')];if(kind==='tickets')cells=[e(x.name),money(x.price),x.quantity+' vé<br>'+badge(x.status)];return `<tr>${cells.map(c=>`<td>${c}</td>`).join('')}<td><div class="actions">${btn('edit-'+kind,'Sửa',x.id)}${btn('delete-'+kind,kind==='sessions'?'Hủy':'Xóa',x.id,'danger')}</div></td></tr>`;}));}
 $('#manage-search').addEventListener('input',update);update();
}
function alerts(){$('#content').innerHTML=heading('Thông báo sự kiện','Tạo thông báo, lưu nháp và mô phỏng phát hành.',role==='organizer'?btn('new-alert','+ Tạo thông báo','','primary'):'')+`<div class="panel">${state().alerts.filter(a=>role==='organizer'||a.status==='Đã gửi').map(a=>`<article class="alert-item">${badge(a.priority,a.priority==='Khẩn cấp')} ${badge(a.status)}<h3>${e(a.title)}</h3><p>${e(a.message)}</p>${role==='organizer'?`${a.status==='Nháp'?btn('publish-alert','Phát hành',a.id,'primary'):''} ${btn('delete-alert','Xóa',a.id,'danger')}`:''}</article>`).join('')||empty('Chưa có thông báo')}</div>`;}
function forecast(){$('#content').innerHTML=heading('Dự báo mức quan tâm','Ước lượng nhu cầu từ lượt đặt, quan tâm và phản hồi giả lập.')+`<div class="two-col"><section class="panel"><h2>✧ Interest Forecast</h2><form id="forecast-form" class="stack">${select('topic','Phạm vi',['Tất cả chủ đề','AI & Data','Product','Fintech'])}<button class="primary" type="submit">Phân tích dữ liệu</button></form><p class="ai-note">AI mô phỏng · Không phải dự báo từ mô hình học máy. Độ tin cậy phụ thuộc số phản hồi.</p></section><section class="panel" id="forecast-results"><h2>Kết quả dự báo</h2><p class="muted">Chọn phạm vi và bắt đầu phân tích.</p></section></div>`;$('#forecast-form').addEventListener('submit',async ev=>{ev.preventDefault();const topic=ev.target.elements.topic.value;const b=ev.target.querySelector('button');b.disabled=true;$('#forecast-results').innerHTML='<div class="loading">Đang phân tích dữ liệu…</div>';await new Promise(r=>setTimeout(r,650));const rows=EventAI.forecast(sessions().filter(s=>topic==='Tất cả chủ đề'||s.topic===topic));$('#forecast-results').innerHTML='<h2>Kết quả dự báo</h2>'+rows.map(r=>`<div class="result"><strong>${e(r.session.title)}</strong><p>Dự báo <b>${r.predicted}</b> người / ${r.session.capacity} chỗ · ${badge(r.ratio>1?'Nguy cơ quá tải':'Đủ sức chứa',r.ratio>1)}</p><p>${e(r.reason)}</p><small>Độ tin cậy: ${r.confidence}. Sai số chưa được kiểm chứng.</small>${r.ratio>1?`<p>${btn('forecast-room','Xem phương án đổi phòng',r.session.id)}</p>`:''}</div>`).join('')||empty('Không đủ dữ liệu để dự báo');b.disabled=false;});}
function analytics(){const s=sessions(),booked=s.reduce((n,s)=>n+s.booked,0),cap=s.reduce((n,s)=>n+s.capacity,0);$('#content').innerHTML=heading('Phân tích sự kiện','Tổng quan hoạt động từ dữ liệu hiện tại trong demo.',btn('export-sessions','Xuất báo cáo'))+stats([['Session',s.length],['Lượt đặt',booked],['Tỷ lệ lấp đầy',cap?Math.round(booked/cap*100)+'%':'0%'],['Người dùng',state().users.length]])+`<div class="grid-two"><section class="panel"><h2>Mức độ lấp đầy theo session</h2><div class="bars">${s.map(x=>`<div class="bar-row"><span>${e(x.title)}</span><div class="bar"><i style="width:${Math.min(100,x.booked/x.capacity*100)}%"></i></div><strong>${Math.round(x.booked/x.capacity*100)}%</strong></div>`).join('')||empty('Chưa có session')}</div></section><section class="panel"><h2>Quan tâm theo chủ đề</h2>${table(['Chủ đề','Session','Lượt đặt'],[...new Set(s.map(x=>x.topic))].map(t=>`<tr><td>${e(t)}</td><td>${s.filter(x=>x.topic===t).length}</td><td>${s.filter(x=>x.topic===t).reduce((n,x)=>n+x.booked,0)}</td></tr>`))}<p class="ai-note">Lượt đặt tính theo session; một người có thể đặt nhiều session.</p></section></div>`;}
function settings(){const s=state().settings;$('#content').innerHTML=heading('Cấu hình & Audit','Thiết lập sự kiện và theo dõi thay đổi trong trình duyệt.')+`<div class="two-col"><section class="panel"><h2>Cấu hình sự kiện</h2><form id="settings-form" class="stack">${field('event','Tên sự kiện *',s.event,'text','required maxlength="120"')}${field('location','Địa điểm *',s.location,'text','required maxlength="120"')}<label><span><input type="checkbox" name="notifications" ${s.notifications?'checked':''}> Bật thông báo demo</span></label><button type="submit" class="primary">Lưu cấu hình</button></form><hr><h2>Dữ liệu demo</h2><p>Khôi phục sẽ thay thế toàn bộ thay đổi trong trình duyệt bằng dữ liệu mẫu.</p>${btn('reset-data','Khôi phục dữ liệu mẫu','','danger')}</section><section class="panel"><h2>Nhật ký hoạt động</h2>${state().audit.slice(0,15).map(a=>`<div class="alert-item"><strong>${e(a.message)}</strong><br><small>${e(a.at)}</small></div>`).join('')||empty('Chưa có thay đổi')}</section></div>`;$('#settings-form').addEventListener('submit',ev=>{ev.preventDefault();const d=new FormData(ev.target);if(!d.get('event').trim()||!d.get('location').trim()){toast('Tên và địa điểm không được để trống.');return;}state().settings={event:d.get('event').trim(),location:d.get('location').trim(),notifications:d.has('notifications')};persist('Đã lưu cấu hình');shell();render();});}
const views={'attendee-session-catalog':catalog,'attendee-session-detail':detail,'attendee-my-agenda':myAgenda,'attendee-session-feedback':feedback,'speaker-profile':profile,'speaker-my-session':speakerSessions,'speaker-session-materials':materials,'speaker-session-insights':insights,'organizer-session-management':()=>management('sessions'),'organizer-room-management':()=>management('rooms'),'organizer-event-alerts':alerts,'organizer-interest-forecast':forecast,'admin-ticket-type-management':()=>management('tickets'),'admin-user-management':()=>management('users'),'admin-event-analytics':analytics,'admin-system-settings':settings};
function render(){(views[route]||(()=>$('#content').innerHTML=heading('Không tìm thấy trang','Hãy quay lại danh mục session.',link('attendee-session-catalog','Trang chủ'))))();}
function addAgenda(id){const s=sessions().find(s=>s.id===id);if(!s)return;if(state().agenda.includes(id))return;if(s.booked>=s.capacity){toast('Session đã đầy. Vui lòng tham gia danh sách chờ.');return;}state().agenda.push(id);s.booked++;s.saves++;persist(EventAI.conflicts(agenda()).length?'Đã thêm lịch · Có xung đột, kiểm tra Agenda.':'Đã thêm vào agenda');render();}
function removeAgenda(id){const s=state().sessions.find(s=>s.id===id);if(state().agenda.includes(id)&&s){s.booked=Math.max(0,s.booked-1);s.saves=Math.max(0,s.saves-1);}state().agenda=state().agenda.filter(x=>x!==id);persist('Đã bỏ khỏi agenda');render();}
function confirmAction(title,text,callback){modal(title,`<p>${e(text)}</p><div class="form-actions">${btn('close','Quay lại')}<button type="button" id="confirm" class="danger">Xác nhận</button></div>`);$('#confirm').addEventListener('click',()=>{$('#modal').close();callback();});}
function editEntity(kind,id,speakerOnly=false){const item=state()[kind].find(x=>x.id===id)||{},isNew=!item.id;let fields='';
 if(kind==='sessions')fields=field('title','Tên session *',item.title,'text','required maxlength="200"')+select('topic','Chủ đề',['AI & Data','Product','Fintech'],item.topic)+field('speaker','Diễn giả *',item.speaker||state().profile.name,'text','required maxlength="100"')+field('date','Ngày *',item.date||'2026-10-19','date','required min="2026-10-18" max="2026-10-20"')+field('start','Bắt đầu *',item.start||'09:00','time','required')+field('end','Kết thúc *',item.end||'10:00','time','required')+select('room','Phòng',state().rooms.map(r=>r.name),item.room)+select('status','Trạng thái',['Chờ duyệt','Đã duyệt','Hoàn thành','Bị từ chối','Đã hủy'],item.status||'Chờ duyệt')+`<label class="full">Mô tả<textarea name="description" maxlength="3000">${e(item.description||'')}</textarea></label>`;
 if(speakerOnly)fields=field('title','Tên session *',item.title,'text','required maxlength="200"')+`<label class="full">Nội dung *<textarea name="description" required maxlength="3000">${e(item.description)}</textarea></label>`;
 if(kind==='rooms')fields=field('name','Tên phòng *',item.name,'text','required maxlength="100"')+field('capacity','Sức chứa *',item.capacity||120,'number','required min="1" max="10000" step="1"')+field('location','Vị trí *',item.location,'text','required maxlength="200"');
 if(kind==='users')fields=field('name','Họ tên *',item.name,'text','required maxlength="100"')+field('email','Email *',item.email,'email','required')+select('role','Vai trò',Object.values(groups).map(g=>g[0]),item.role)+select('status','Trạng thái',['Hoạt động','Tạm khóa'],item.status);
 if(kind==='tickets')fields=field('name','Tên loại vé *',item.name,'text','required maxlength="100"')+field('price','Giá vé (VNĐ) *',item.price??299000,'number','required min="0" max="100000000" step="1000"')+field('quantity','Số lượng *',item.quantity??100,'number','required min="0" max="100000" step="1"')+select('status','Trạng thái',['Đang bán','Tạm dừng','Đã hết'],item.status);
 modal((isNew?'Thêm mới':'Chỉnh sửa')+' · '+({sessions:'Session',rooms:'Phòng',users:'Người dùng',tickets:'Loại vé'}[kind]),`<form id="entity-form" class="form-grid">${fields}<p id="form-error" class="error full" role="alert"></p><div class="form-actions full">${btn('close','Hủy')}<button type="submit" class="primary">Lưu thay đổi</button></div></form>`);
 $('#entity-form').addEventListener('submit',ev=>{ev.preventDefault();const d=Object.fromEntries(new FormData(ev.target));for(const k in d)d[k]=d[k].trim();const error=msg=>{$('#form-error').textContent=msg;};if(Object.entries(d).some(([k,v])=>!v&&k!=='description'))return error('Vui lòng nhập đầy đủ nội dung.');for(const k of ['capacity','price','quantity'])if(k in d)d[k]=Number(d[k]);
 if(kind==='rooms'&&state().rooms.some(r=>r.id!==id&&r.name.toLowerCase()===d.name.toLowerCase()))return error('Tên phòng đã tồn tại.');
 if(kind==='rooms'&&sessions().some(s=>s.room===item.name&&s.booked>d.capacity))return error('Sức chứa mới nhỏ hơn số người đã đặt.');
 if(kind==='users'&&state().users.some(u=>u.id!==id&&u.email.toLowerCase()===d.email.toLowerCase()))return error('Email đã tồn tại.');
 if(kind==='sessions'&&!speakerOnly){if(d.start>=d.end)return error('Giờ kết thúc phải sau giờ bắt đầu.');const room=state().rooms.find(r=>r.name===d.room);if(!room)return error('Hãy tạo phòng trước khi tạo session.');if((item.booked||0)>room.capacity)return error('Phòng không đủ chỗ cho người đã đặt.');if(d.status!=='Đã hủy'&&sessions().some(s=>s.id!==id&&EventAI.overlap(s,d)&&(s.room===d.room||s.speaker===d.speaker)))return error('Trùng thời gian phòng hoặc diễn giả. Hãy chọn khung giờ khác.');d.capacity=room.capacity;d.image=d.topic==='Product'?'product':d.topic==='Fintech'?'fintech':'ai';}
 if(isNew)state()[kind].push({id:Date.now(),...(kind==='sessions'?{booked:0,saves:0,feedbackCount:0}:{}),...d});else{const oldName=item.name;Object.assign(item,d);if(kind==='rooms')state().sessions.filter(s=>s.room===oldName).forEach(s=>{s.room=d.name;s.capacity=d.capacity;});if(kind==='sessions'&&d.status==='Đã hủy'){state().agenda=state().agenda.filter(x=>x!==id);state().waitlist=state().waitlist.filter(x=>x!==id);}}
 $('#modal').close();persist('Đã lưu '+({sessions:'session',rooms:'phòng',users:'người dùng',tickets:'loại vé'}[kind]));render();});
}
function recommend(){modal('✧ Agenda Recommender',`<form id="recommend-form" class="stack">${field('interests','Chủ đề hoặc mục tiêu *','','text','required minlength="2" maxlength="200" placeholder="Ví dụ: AI, Product, Fintech"')}<button type="submit" class="primary">Tìm session phù hợp</button></form><div id="ai-results"></div><p class="ai-note">AI mô phỏng: so khớp từ khóa trong tiêu đề / chủ đề, loại session hết chỗ và trùng agenda.</p>`);$('#recommend-form').addEventListener('submit',async ev=>{ev.preventDefault();const terms=ev.target.elements.interests.value.trim();if(terms.length<2){toast('Nhập tối thiểu 2 ký tự.');return;}const b=ev.target.querySelector('button');b.disabled=true;$('#ai-results').innerHTML='<div class="loading">Đang tìm nội dung phù hợp…</div>';await new Promise(r=>setTimeout(r,650));if(!$('#ai-results'))return;const results=EventAI.recommend(sessions(),terms,agenda());$('#ai-results').innerHTML=results.map(r=>`<div class="result"><strong>${e(r.session.title)}</strong><p>Phù hợp ${r.score} từ khóa; còn chỗ và không trùng lịch hiện tại.</p>${btn('accept-recommend','Chấp nhận',r.session.id,'primary')} ${btn('dismiss-result','Bỏ qua')}</div>`).join('')||`<div class="result"><strong>Chưa đủ cơ sở để gợi ý</strong><p>Không có session phù hợp với từ khóa, sức chứa và lịch hiện tại. Đổi từ khóa hoặc chỉnh agenda rồi thử lại.</p></div>`;b.disabled=false;});}
function resolve(){const results=EventAI.resolve(agenda());if(!results.removed.length){toast('Không có xung đột trong agenda hiện tại.');return;}modal('✧ Đề xuất giải quyết xung đột',`<p>Ưu tiên giữ phiên bắt đầu sớm hơn, bỏ các phiên trùng thời gian:</p>${results.removed.map(s=>`<div class="result"><strong>${e(s.title)}</strong><p>${e(s.start)}–${e(s.end)} · ${e(s.room)}</p></div>`).join('')}<p class="ai-note">Mức tin cậy: trung bình. Đây là quy tắc thời gian; bạn có thể bỏ qua và tự chỉnh agenda.</p><div class="form-actions">${btn('close','Bỏ qua')}<button type="button" id="apply-resolve" class="primary">Áp dụng đề xuất</button></div>`);$('#apply-resolve').addEventListener('click',()=>{$('#modal').close();results.removed.forEach(s=>{s.booked=Math.max(0,s.booked-1);s.saves=Math.max(0,s.saves-1);});state().agenda=results.accepted.map(s=>s.id);persist('Đã áp dụng lịch không trùng thời gian');render();});}
function newAlert(){modal('Tạo thông báo',`<form id="alert-form" class="stack">${field('title','Tiêu đề *','','text','required maxlength="150"')}<label>Nội dung *<textarea name="message" required minlength="10" maxlength="2000"></textarea></label>${select('priority','Mức độ',['Thông tin','Quan trọng','Khẩn cấp'])}${select('status','Trạng thái',['Nháp','Đã gửi'])}<button type="submit" class="primary">Lưu thông báo</button></form>`);$('#alert-form').addEventListener('submit',ev=>{ev.preventDefault();const d=Object.fromEntries(new FormData(ev.target));if(!d.title.trim()||d.message.trim().length<10){toast('Nhập tiêu đề và nội dung tối thiểu 10 ký tự.');return;}state().alerts.unshift({id:Date.now(),...d});$('#modal').close();persist(d.status==='Nháp'?'Đã lưu nháp thông báo':'Đã phát hành thông báo demo');render();});}
function forecastRoom(id){const s=sessions().find(s=>s.id===id);const prediction=EventAI.forecast([s])[0];const rooms=state().rooms.filter(r=>r.capacity>=prediction.predicted&&!sessions().some(other=>other.id!==id&&other.room===r.name&&EventAI.overlap(s,other)));modal('Phương án đổi phòng',`<p>Dự báo ${prediction.predicted} người. Chỉ đề xuất phòng đủ sức chứa và không trùng thời gian.</p>${rooms.map(r=>`<div class="result"><strong>${e(r.name)}</strong><p>${r.capacity} chỗ · ${e(r.location)}</p><button type="button" class="primary" data-action="apply-room" data-id="${s.id}" data-room="${r.id}">Chấp nhận đổi phòng</button></div>`).join('')||'<p class="error">Không có phòng phù hợp. Hãy bổ sung phòng hoặc chỉnh lịch thủ công.</p>'}${btn('close','Bỏ qua')}`);}
document.addEventListener('click',ev=>{const el=ev.target.closest('[data-action]');if(!el)return;ev.preventDefault();const a=el.dataset.action,id=Number(el.dataset.id);
 if(a==='close')return $('#modal').close();if(a==='menu'){$('#sidebar').classList.toggle('open');el.setAttribute('aria-expanded',$('#sidebar').classList.contains('open'));return;}
 if(a==='help')return modal('Hướng dẫn demo',`<p>Chọn vai trò ở cuối thanh bên để truy cập 16 màn hình. Dữ liệu dùng chung được lưu trong LocalStorage.</p><p>Thử tìm và thêm session → kiểm tra Agenda → gửi phản hồi. Với ban tổ chức, tạo session / phòng và chạy dự báo để xem phương án đổi phòng.</p><p>Ba tính năng AI sử dụng quy tắc giả lập. Vai trò demo không phải cơ chế đăng nhập hay phân quyền bảo mật.</p>${btn('close','Đã hiểu','','primary')}`);
 if(a==='notifications')return modal('Thông báo',state().settings.notifications?state().alerts.filter(a=>a.status==='Đã gửi').map(a=>`<div class="result"><strong>${e(a.title)}</strong><p>${e(a.message)}</p></div>`).join('')||empty('Chưa có thông báo'):'<p>Bạn đã tắt thông báo trong cấu hình.</p>');
 if(a==='add-agenda')return addAgenda(id);if(a==='remove-agenda')return removeAgenda(id);
 if(a==='waitlist'){state().waitlist=state().waitlist.includes(id)?state().waitlist.filter(x=>x!==id):[...state().waitlist,id];persist('Đã cập nhật danh sách chờ');render();return;}
 if(a==='grid'||a==='list'){$('#catalog').classList.toggle('list',a==='list');return;}
 if(a==='reset-filters'){for(const n of ['search','date','topic','speaker','availability'])$('#'+n).value='';filterCatalog();return;}
 if(a==='recommend')return recommend();if(a==='resolve')return resolve();
 if(a==='accept-recommend'){const s=sessions().find(s=>s.id===id);if(!s||agenda().some(x=>EventAI.overlap(x,s))){toast('Agenda đã thay đổi. Hãy chạy lại gợi ý.');return;}addAgenda(id);el.closest('.result').remove();return;}
 if(a==='dismiss-result'){el.closest('.result').remove();return;}
 if(a==='draft-feedback')return saveFeedback('Nháp');
 if(a==='delete-feedback')return confirmAction('Xóa phản hồi','Bạn muốn xóa phản hồi và bản nháp?',()=>{const f=state().feedback.find(f=>f.id==='personal');if(f?.status==='Đã gửi'){const s=state().sessions.find(s=>s.id===f.sessionId);if(s)s.feedbackCount=Math.max(0,s.feedbackCount-1);}state().feedback=state().feedback.filter(f=>f.id!=='personal');persist('Đã xóa phản hồi');render();});
 if(a==='delete-material')return confirmAction('Xóa tài liệu','Xóa thông tin tài liệu khỏi demo?',()=>{state().materials=state().materials.filter(m=>m.id!==id);persist('Đã xóa thông tin tài liệu');render();});
 if(a==='speaker-edit')return editEntity('sessions',id,true);
 if(a.startsWith('create-'))return editEntity(a.slice(7),0);
 if(a.startsWith('edit-'))return editEntity(a.slice(5),id);
 if(a.startsWith('export-')){const kind=a.slice(7);EP.export('eventpulse-'+kind,kind==='agenda'?agenda():state()[kind]||[]);toast('Đã xuất CSV');return;}
 if(a==='new-alert')return newAlert();
 if(a==='publish-alert'){state().alerts.find(x=>x.id===id).status='Đã gửi';persist('Đã phát hành thông báo demo');render();return;}
 if(a==='delete-alert')return confirmAction('Xóa thông báo','Bạn muốn xóa thông báo này?',()=>{state().alerts=state().alerts.filter(x=>x.id!==id);persist('Đã xóa thông báo');render();});
 if(a==='forecast-room')return forecastRoom(id);
 if(a==='apply-room'){const s=sessions().find(s=>s.id===id),r=state().rooms.find(r=>r.id===Number(el.dataset.room));s.room=r.name;s.capacity=r.capacity;$('#modal').close();persist('Đã đổi phòng session sang '+r.name);render();return;}
 if(a==='reset-data')return confirmAction('Khôi phục dữ liệu mẫu','Mọi thay đổi trong demo sẽ được thay bằng dữ liệu mẫu. Tiếp tục?',()=>{EP.reset();shell();render();toast('Đã khôi phục dữ liệu mẫu');});
 if(a.startsWith('delete-')){const kind=a.slice(7);const item=state()[kind].find(x=>x.id===id);if(kind==='rooms'&&sessions().some(s=>s.room===item.name)){toast('Phòng đang có session. Chuyển session sang phòng khác trước khi xóa.');return;}return confirmAction(kind==='sessions'?'Hủy session':'Xóa dữ liệu','Bạn muốn '+(kind==='sessions'?'hủy session này?':'xóa mục này?'),()=>{if(kind==='sessions'){item.status='Đã hủy';state().agenda=state().agenda.filter(x=>x!==id);state().waitlist=state().waitlist.filter(x=>x!==id);}else state()[kind]=state()[kind].filter(x=>x.id!==id);persist(kind==='sessions'?'Đã hủy session':'Đã xóa dữ liệu');render();});}
});
document.addEventListener('keydown',ev=>{if(ev.key==='Escape'){$('#sidebar').classList.remove('open');$('.menu-toggle')?.setAttribute('aria-expanded','false');}});
shell();render();if(EP.warning)toast(EP.warning);
})();
